services:
  panel:
    hostname: panel
    stop_grace_period: 1s
    build:
      context: .
      dockerfile: panel.Dockerfile
    networks:
      - ptero_network
    volumes:
      - type: bind
        source: ./nginx-default.conf
        target: /etc/nginx/conf.d/default.conf
        consistency: consistent
        read_only: true
      - type: bind
        source: .env
        target: /var/www/pterodactyl/.env
        consistency: consistent
    env_file:
      - ./.env
    environment:
      - SERVER_NAME
    depends_on:
      - redis
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.panel.rule=Host(`${SERVER_NAME}`)"
      - "traefik.http.routers.panel.entrypoints=web"




  traefik:
    image: traefik:v3.0.0-beta5
    command:
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--api.dashboard=true"
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
        host_ip: ${HOST_IP:-127.0.0.1}
      - target: 8080 # Traefik Dashboard
        published: 8080
        protocol: tcp
        mode: host
        host_ip: ${HOST_IP:-127.0.0.1}
    env_file:
      - ./.env
    environment:
      - HOST_IP
    networks:
      - ptero_network
    depends_on:
      - panel
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`traefik`)"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.entrypoints=web"
  redis:
    hostname: redis
    image: redis:7.2.3-alpine3.18
    volumes:
      - type: volume
        source: redis_data
        target: /data
    networks:
      - ptero_network
  mariadb:
    image: mariadb:10.5
    hostname: mariadb
    volumes:
      - type: volume
        source: mariadb_data
        target: /var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=ptero
      - MARIADB_DATABASE=ptero
      - MARIADB_USER=ptero
      - MARIADB_PASSWORD=ptero
    networks:
      - ptero_network

networks:
  ptero_network:
volumes:
  redis_data:
  mariadb_data:
  wing_data:
